services:
  # Configuración del Backend (Flask)
  - type: web
    name: backend-service
    env: python
    buildCommand: "pipenv install" # Instala las dependencias del backend
    startCommand: "pipenv run start" # Comando para iniciar Flask
    region: ohio
    plan: free
    numInstances: 1
    envVars:
      - key: BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py # Asegúrate de que tu archivo principal está aquí
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

  # Configuración del Frontend (React)
  - type: web
    name: frontend-service
    env: static
    buildCommand: "npm install && npm run build" # Construye el frontend
    staticPublishPath: build # Carpeta donde React genera los archivos estáticos
    region: ohio
    plan: free
    numInstances: 1
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://backend-service.onrender.com" # Cambia por la URL de tu backend desplegado

databases:
  # Configuración de la base de datos PostgreSQL
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: [] # Permite solo conexiones internas
    plan: free
